### ISSUE TITLE
Is it supposed to work with python 2?

### ISSUE THREAD

**Issue by xerus2000** [tbabej/taskpirate#10]
I am unable to get it to work properly. It depends on functools (which should be mentioned in the readme) which I don't get working in Python 2, but the shebang implies Python 2 (at least on Ubuntu). 

After installing functools and changing the shebang it finally worked.

**Comment by narq** [comment]
My system python is 3.7.   Obviously python2 is no longer supported by the python project since january 1st this year.  But I can't get taskpirate or tasklib to work with either python2 (by changing the shebang) or python3.
